REGISTRATION_EMAIL = "Registration Email"
PASSWORD_RESET_EMAIL = "Password Reset Email"

PENDING = "Pending"

MICRO = "micro"
NANO = "nano"
REGIONAL = "regional"
BREWPUB = "brewpub"
LARGE = "large"
PLANNING = "planning"
BAR = "bar"
CONTRACT = "contract"
PROPRIETOR = "proprietor"
CLOSED = "closed"
