# Generated by Django 4.2.4 on 2023-08-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cardUserKey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_user_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mobile_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kvkk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tckn',
        ),
    ]
