# Generated by Django 4.2.4 on 2023-08-20 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Registration Email', 'Registration Email'), ('Password Reset Email', 'Password Reset Email')], max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=25000, null=True)),
                ('to_email', models.CharField(blank=True, max_length=500, null=True)),
                ('bcc', models.CharField(blank=True, max_length=500, null=True)),
                ('cc', models.CharField(blank=True, max_length=500, null=True)),
                ('from_email', models.CharField(blank=True, max_length=500, null=True)),
                ('from_user', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
                'ordering': ['-pk'],
            },
        ),
    ]
